name: sciprog
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.13  # https://anaconda.org/channels/main/packages/python/overview
  - pip=26.1.1      # https://anaconda.org/channels/conda-forge/packages/pip/overview
  - pip:
      - uv==0.11.9
